packages:
  - data
  - schema
  - server
  - eslint-config

catalog:
  '@eslint/js': 10.0.1
  '@stylistic/eslint-plugin': 5.9.0
  '@types/node': 24.10.13
  eslint: 10.0.1
  eslint-plugin-jsdoc: 62.7.0
  eslint-plugin-unicorn: 63.0.0
  graphql: 16.12.0
  tsup: 8.5.1
  tsx: 4.21.0
  turbo: 2.8.10
  typescript: 5.9.3
  typescript-eslint: 8.56.0

gitBranchLockfile: true

mergeGitBranchLockfilesBranchPattern:
  - main
  - release-please--*
