packages:
  - data
  - schema
  - server
  - eslint-config

catalog:
  '@eslint/js': 9.39.2
  '@stylistic/eslint-plugin': 5.7.1
  '@types/node': 24.10.9
  eslint: 9.39.2
  eslint-plugin-jsdoc: 62.5.0
  eslint-plugin-unicorn: 62.0.0
  graphql: 16.12.0
  tsup: 8.5.1
  tsx: 4.21.0
  turbo: 2.8.1
  typescript: 5.9.3
  typescript-eslint: 8.54.0

gitBranchLockfile: true

mergeGitBranchLockfilesBranchPattern:
  - main
  - release-please--*
