packages:
  - data
  - schema
  - server
  - eslint-config
gitBranchLockfile: true
mergeGitBranchLockfilesBranchPattern:
  - main
  - release-please--*
catalog:
  "@eslint/js": 9.39.1
  "@stylistic/eslint-plugin": 5.6.1
  "@types/node": 24.10.1
  eslint: 9.39.1
  eslint-plugin-jsdoc: 61.4.1
  eslint-plugin-unicorn: 62.0.0
  graphql: 16.12.0
  tsup: 8.5.1
  tsx: 4.21.0
  turbo: 2.6.3
  typescript: 5.9.3
  typescript-eslint: 8.48.1
